// <auto-generated />
using System;
using LinqPractice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinqPractice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230108091258_BookUpgrade")]
    partial class BookUpgrade
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LinqPractice.Models.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("LinqPractice.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LinqPractice.Models.MuseumObject", b =>
                {
                    b.Property<string>("ObjectInventoryNumber")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ObjectCreationDate")
                        .HasColumnType("int");

                    b.Property<string>("ObjectCreator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectPersistentIdentifier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ObjectInventoryNumber");

                    b.ToTable("MuseumObjects");
                });

            modelBuilder.Entity("LinqPractice.Models.Book", b =>
                {
                    b.HasOne("LinqPractice.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
