// <auto-generated />
using LinqPractice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinqPractice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230106184404_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LinqPractice.Models.MuseumObject", b =>
                {
                    b.Property<string>("ObjectInventoryNumber")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ObjectCreationDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectCreator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectPersistentIdentifier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ObjectInventoryNumber");

                    b.ToTable("MuseumObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
